### ISSUE TITLE
Council command not showing councils

### ISSUE THREAD

**Issue by NiteBlock** [bridge-scrims/bridge-scrims-bot#47] opened 2022-03-09 06:10 UTC
The council command occasionally only had the title, I believe reloading could be the issue

**Comment by NiteBlock** [comment] 2022-03-09 06:10
![image](https://user-images.githubusercontent.com/47315009/157382860-3a213ea0-3c0f-420f-a697-05510fff3b69.png)

**Comment by dtomvan** [comment] 2022-03-13 10:54
We cannot reproduce. Closing for now

**Closed by dtomvan** 2022-03-13 10:54 UTC
Labels: bug, invalid

**Comment by dtomvan** [comment] 2022-03-13 10:59
Nite:
> Yes, I think the splitting of init and reload fixed it

Fixed in [26d79de](https://github.com/bridge-scrims/bridge-scrims-bot/commit/26d79dee30115c0f9b12dbe31b9152839690e6a2)
